### ISSUE TITLE
Modal Action 'confirmation' option

### ISSUE THREAD

**Issue by ArnoEgli** [whatwedo/CoreBundle#14]
The option "confirmation" does not exist. Defined options are: "block_prefix", "label", "attr", "icon", "route", "route_parameters", "voter_attribute", "priority", "visibility".

https://github.com/whatwedo/CoreBundle/blob/872512deb15b9fa31f4274984e69bea741fdbdca/src/Action/ModalAction.php#L30-L41

https://github.com/whatwedo/CoreBundle/blob/872512deb15b9fa31f4274984e69bea741fdbdca/src/Action/Action.php#L15-L24

**Comment by tuxes3** [comment]
This should work now. The confirmation is not yet implemented on the `ModalAction`. We are working on it!
