### ISSUE TITLE
Implementierung CollectionFormatter

### ISSUE THREAD

**Issue by n3r0-ch** [whatwedo/CoreBundle#3]
Der `CollectionFormatter` vebindet aktuell ohne Leerzeichen und nur mit Komma. Ich schlage vor das Verhalten von `implode(',', $value)` nach `implode(', ', $value)` anzupassen. Ziel ist eine bessere Lesbarkeit. Was meint ihr?

**Comment by xarem** [comment]
Für mich i.O.

Im getString() wird jedoch bei der Eingabe eines Iterators einfach ein leerer String returned. Dies würde ich anpassen. Zudem den `ArrayFormatter` abzuschiessen, da dieser keinen Sinn macht meines Erachtens.
